# Temporarily disabled to stop email spam
# To re-enable, uncomment the configuration below

version: 2
updates: []

# Original configuration (uncomment to re-enable):
# version: 2
# updates:
#   # Enable version updates for npm
#   - package-ecosystem: "npm"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#       time: "10:00"
#     open-pull-requests-limit: 10
#     reviewers:
#       - "DrunkOnJava"
#     labels:
#       - "dependencies"
#       - "npm"
#     commit-message:
#       prefix: "chore"
#       include: "scope"
#     allow:
#       - dependency-type: "production"
#       - dependency-type: "development"
#     ignore:
#       # Ignore major version updates for these packages
#       - dependency-name: "react"
#         update-types: ["version-update:semver-major"]
#       - dependency-name: "react-dom"
#         update-types: ["version-update:semver-major"]
#     groups:
#       # Group all development dependencies together
#       dev-dependencies:
#         patterns:
#           - "@types/*"
#           - "eslint*"
#           - "prettier*"
#           - "vitest*"
#         update-types:
#           - "minor"
#           - "patch"
#       # Group all Radix UI updates together
#       radix-ui:
#         patterns:
#           - "@radix-ui/*"
#         update-types:
#           - "minor"
#           - "patch"
#
#   # Enable version updates for GitHub Actions
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#       day: "monday"
#       time: "10:00"
#     reviewers:
#       - "DrunkOnJava"
#     labels:
#       - "dependencies"
#       - "github-actions"
#     commit-message:
#       prefix: "ci"
#       include: "scope"