blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/DrunkOnJava/MaterialMDashboard/discussions
    about: Please ask and answer questions here
  - name: 📚 Documentation
    url: https://github.com/DrunkOnJava/MaterialMDashboard/wiki
    about: Check out our documentation for guides and API references
  - name: 💼 Security Issues
    url: https://github.com/DrunkOnJava/MaterialMDashboard/security/policy
    about: Please report security vulnerabilities here